services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
      - mosquitto
    ports:
      - "4000:4000"
    volumes:
      - api_certs:/app/certs

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_APP_MODE: public
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8081:80"

  web_company:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_APP_MODE: company
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  mongo_data:
  mosquitto_data:
  api_certs:
